version: 2
updates:
  # rage4j
  - package-ecosystem: "maven"
    directory: "/dev.rage4j.rage4j"
    schedule:
      interval: "daily"

  # rage4j-assert
  - package-ecosystem: "maven"
    directory: "/dev.rage4j.rage4j-assert"
    schedule:
      interval: "daily"

  # docusaurus
  - package-ecosystem: "npm"
    directory: "/docusaurus"
    schedule:
      interval: "daily"
